### PR TITLE
[mrt128] Modify guest login process to prevent redirect to http

### PR DESCRIPTION
**Pull request by terrywbrady**
See https://github.com/CDLUC3/mrt-doc/issues/128

### CODE REVIEW

**Comment by terrywbrady** [comment]
My changes to the login form did not help this issue, so I have reverted that commit.

The travis changes are likely still needed, so those are being retained.

**Comment by terrywbrady** [comment]
The coverage checks required me to write a new test for the store_location method.  Unfortunately, it was difficult to set the request URL for this method, so I had to complicate the logic a bit.  I would like to review this with folks and create a cleaner implementation.

**Comment by briri** [comment]
I'm not quite sure in what context the function is used, so this may or may not be a useful adjustment :)
`fullpath` is only going to give you the path portion of the URL (e.g. 'path/to/file' from 'https://merritt.org/path/to/file') so the protocol should never be a factor.

Take a look at Ruby's [URI module](https://docs.ruby-lang.org/en/2.1.0/URI.html) and the [ActionDispatch::Request class](https://api.rubyonrails.org/classes/ActionDispatch/Request.html).

Something like this might be a little cleaner (assuming that the sole purpose of this method is to ensure that session variable is always https when your tests would run as http by default):
```ruby
def store_location(force_https = false)
  # If we don't need to force it, just return whatever the request has
  return request.original_url unless force_https || APP_CONFIG['port_force']

  # force SSL
  uri = URI.parse(request.original_url)
  uri.scheme = "https"
  session[:return_to] = uri.to_s
rescue URI::InvalidURIError 
  # something was wrong with the URL!
end
```

**Comment by terrywbrady** [comment]
Thanks @briri . I like your suggestion for changing the url scheme.  I think the updated code is cleaner.

**Comment by terrywbrady** [comment]
Change deployed on Jan 30, 2020.  Changes looks successful.

**Pull request merged**
