### PR TITLE
Localids not dublinkernels

### PR DESCRIPTION
**Pull request by dmolesUC3**
For objects, display local IDs from the `inv_localids` table, instead of displaying the latest version's `inv_dublinkernels` "where" attribute.

Also, for the object Atom feed, generate one `<link rel="alternate">` for each HTTP(s) local ID in an object, instead of only checking the first local ID from the current version.

**Note:** This change doesn't touch the version detail display, which still uses `inv_dublinkernels`.

### CODE REVIEW

**Comment by mreyescdl** [comment]
Hi David,
I deployed to stage and am not seeing the local ID at the object level.  They are visible at the version level which you state still uses the DK table.  Here is an example.  Can you have a look

https://merritt-stage.cdlib.org/m/ark%253A%252F28722%252Fk2d21rj8j

**Comment by dmolesUC3** [comment]
Looks like I didn’t set up the foreign keys properly in ActiveRecord. Working on it.

--
David Moles
UC Curation Center

**Comment by dmolesUC3** [comment]
OK, I took the time to do it right and add tests etc. as I should have done originally. 🙄 Foreign keys should be fixed now; give it another try.

**Comment by mreyescdl** [comment]
Looks good David.  I'll pull the change into master but hold off on deploying to prod until Monday

**Pull request merged**
